site :opscode

# general
cookbook 'apt'
cookbook 'ntp'
cookbook "yum", "2.2.0"
cookbook "rabbitmq", "2.0.0"
cookbook 'users'

# ha arch nginx
cookbook 'bobcontents', git: 'https://github.com/jedipunkz/bobcontents.git'
cookbook 'nginx.lb', git: 'https://github.com/jedipunkz/cookbook-nginx_lb.git'
cookbook 'nginx', git: 'https://github.com/jedipunkz/cookbook-nginx.git'
cookbook 'chef-client', git: 'https://github.com/jedipunkz/chef-client.git'

# sensu 
cookbook "redis", git: "https://github.com/jedipunkz/chef-redis.git"
cookbook "sensu", git: "https://github.com/jedipunkz/sensu-chef.git"
cookbook "monitor", git: "https://github.com/jedipunkz/chef-monitor.git"
