site :opscode

# general
cookbook 'apt'
cookbook 'ntp'
cookbook "yum", "2.2.0"
cookbook "rabbitmq", "2.0.0"
cookbook 'users'

# ha arch nginx
cookbook 'nginx.lb', git: 'git@gitlab.kddiweb.jp:thirai/cookbook-nginx_lb.git'
cookbook 'nginx', git: 'git@gitlab.kddiweb.jp:thirai/cookbook-nginx.git'
cookbook 'chef-client', git: 'git@gitlab.kddiweb.jp:thirai/cookbook-chef-client.git'
cookbook 'bobcontents', git: 'git@gitlab.kddiweb.jp:thirai/bobcontents.git'

# sensu 
cookbook "redis", git: "https://github.com/jedipunkz/chef-redis.git"
cookbook "sensu", git: "https://github.com/jedipunkz/sensu-chef.git"
cookbook "monitor", git: "https://github.com/jedipunkz/chef-monitor.git"
